

function __(v){return v}//language functiom //todo

// text_effects  yes_no justify align  gap  size  shadow  radius                                
export const options = {
    submenu_style: [
        { v: 'sbs-default', t: `${__('Default') } ` },
        { v: 'sbs-underline', t: `${__('Underline') } ` },
        { v: 'sbs-boxed', t: `${__('Boxed') } ` },
        //will be more
    ],
    submenu: [
        { v: 'de-fade', t: `${__('Default') } ` },
        { v: 'de-swing', t: `${__('Swing') } ` },
        { v: 'de-slide', t: `${__('Slide') } ` },
        //will be more
    ],
    drop_side: [
        { v: 'drop-right', t: `${__('Right') } ` },
        { v: 'drop-left', t: `${__('Left') } ` },
    ],

    lv: [
        { v: 'lv_0', t: `${__('Top') } ` },
        { v: 'lv_1', t: `${__('Submenu Level 1') } ` },
        //will be more
    ],
    target: [
        { v: '_self', t: `${__('Same') } ${__('Window') }` },
        { v: '_blank', t: `${__('New') } ${__('Window') }` },
    ],
    img_st: [
        { v: '', t: __('Default') },
        { v: 'img-circle', t: __('Circle') },
    ],
    f_w: [
        { v: '', t: __('No') },
        { v: 'f-w', t: __('Wrap') },
    ],
    h_ef_b: [
        { v: '', t: __('None') },
        { v: 'e-jump', t: __('Jump') },
        { v: 'e-scale', t: __('Zoom Up') },
        { v: 'e-scale-down', t: `${__('Zoom Down')}` },
    ],
    i_tag: [
        { v: 'div', t: __('Div') },
        { v: 'a', t: __('Link') },
    ],
    tp: [
        { v: '', t: __('Color') },
        { v: 'gradient', t: __('Gradient') },
        { v: 'img', t: __('Image') },
    ],
    tp_no_img: [
        { v: '', t: __('Color') },
        { v: 'gradient', t: __('Gradient') },
    ],
    filter: [
        { v: '', t: __('None') },
        { v: 'o-1', t: '10%' },
        { v: 'o-2', t: '20%' },
        { v: 'o-3', t: '30%' },
        { v: 'o-4', t: '40%' },
        { v: 'o-5', t: '50%' },
        { v: 'o-6', t: '60%' },
        { v: 'o-7', t: '70%' },
        { v: 'o-8', t: '80%' },
        { v: 'o-9', t: '90%' },
    ],
    ssa: [
        { v: 'slide', t: 'slide' },
        { v: 'fade', t: 'fade' },
        { v: 'scale', t: 'scale' },
        { v: 'pull', t: 'pull' },
        { v: 'push', t: 'push' },
    ],
    trg: [
        { v: '_self', t: __('Same window') },
        { v: '_blank', t: __('New window') },
    ],
    media_type: [
        { v: '', t: __('None') },
        { v: 'img', t: __('Image') },
        { v: 'video', t: __('Video') },
    ],
    h_style_less: [
        { v: '', t: __('Default') },
        { v: 'h-underline', t: __('Underline') },
        { v: 'h-underline-light', t: `${__('Underline')}  ${__('Light')}` },
        { v: 'h-bd', t: `${__('Boxed')} ${__('Dark')}` },
        { v: 'h-bl', t: `${__('Boxed')} ${__('Light')}` },
    ],
    h_style: [
        { v: '', t: __('Default') },
        { v: 'h-underline', t: __('Underline') },
        { v: 'h-underline-light', t: `${__('Underline')}  ${__('Light')}` },
        { v: 'h-line', t: __('Line') },
        { v: 'h-line-light', t: `${__('Line')} ${__('Light')}` },
        { v: 'h-bd', t: `${__('Boxed')} ${__('Dark')}` },
        { v: 'h-bl', t: `${__('Boxed')} ${__('Light')}` },
    ],
    logo_type: [
        { v: 'text', t: __('Text') },
        { v: 'img', t: __('Image') },
    ],
    bg_type: [
        { v: '', t: 'None' },
        { v: 'bg', t: 'Background Color' },
        { v: 'gr', t: 'Gradient' },
        { v: 'img', t: 'Image' },
    ],
    dir: [
        { v: 'to bottom', t: 'bottom' },
        { v: 'to top', t: 'top' },
        { v: 'to right', t: 'right' },
        { v: 'to left', t: 'left' },
        { v: 'to top left', t: 'top left' },
        { v: 'to top right', t: 'top right' },
        { v: 'to bottom right', t: 'bottom right' },
        { v: 'to bottom left', t: 'bottom left' },
    ],
    //rmi
    grad_dir: [
        { v: 'to bottom', t: 'bottom' },
        { v: 'to top', t: 'top' },
        { v: 'to right', t: 'right' },
        { v: 'to left', t: 'left' },
        { v: 'to top left', t: 'top left' },
        { v: 'to top right', t: 'top right' },
        { v: 'to bottom right', t: 'bottom right' },
        { v: 'to bottom left', t: 'bottom left' },
    ],
    blank: [
        { v: '', t: 'none' },
        { v: '', t: '' },
    ],
    symbol_mode: [
        { v: '', t: 'None' },
        { v: 'icons', t: 'Icons' },
        { v: 'num', t: 'Numbers' },
    ],
    icon_place: [
        { v: 'icn-bebore', t: 'Before Title' },
        { v: 'icn-after', t: 'After Title' },
        { v: 'icn-above', t: 'Above Title' },
        { v: 'icn-aside', t: 'Aside Left' },
    ],
    effect: [
        { v: '', t: 'none' },
        { v: 'e-shadow', t: 'shadow' },
        { v: 'e-inset', t: 'inset' },
        { v: 'e-glow ', t: 'glow' },
        { v: 'e-neon', t: 'neon' },
        { v: 'e-flame', t: 'flame' },
        { v: 'e-fire', t: 'fire' },
        { v: 'e-blur', t: 'blur' },
        { v: 'e-simple3d', t: 'simple3d' },
        { v: 'e-realistic3d', t: 'realistic3d' },
        { v: 'e-vegas', t: 'vegas' },
        { v: 'e-monument', t: 'monument' },
        { v: 'e-deep', t: 'deep' },
        { v: 'e-tactile', t: 'tactile' },
        { v: 'e-slight ', t: 'slight ' },
        { v: 'e-shadow-glow', t: 'shadow-glow' },
        { v: 'e-blue-shadow', t: 'blue-shadow' },
        { v: 'e-slight-shadow', t: 'slight-shadow' },
    ],
    wc: [
        { v: '', t: 'Auto' },
        { v: 'cw-1-6', t: '16%' },
        { v: 'cw-1-5', t: '20%' },
        { v: 'cw-1-4', t: '25%' },
        { v: 'cw-1-3', t: '33%' },
        { v: 'cw-1-2', t: '50%' },
        { v: 'w-2-3', t: '66%' },
        { v: 'w-3-5', t: '60%' },
        { v: 'w-4-5', t: '80%' },
        { v: 'cw-3-4', t: '75%' },
        { v: 'cw-1-1', t: '100%' },

    ],
    wi: [
        { v: '', t: 'Auto' },
        { v: 'cw-1-6', t: '16%' },//todo!!! check why it's cw
        { v: 'cw-1-5', t: '20%' },
        { v: 'cw-1-4', t: '25%' },
        { v: 'cw-1-3', t: '33%' },
        { v: 'cw-1-2', t: '50%' },
        { v: 'w-3-5', t: '60%' },
        { v: 'w-2-3', t: '66%' },
        { v: 'w-4-5', t: '80%' },
        { v: 'cw-3-4', t: '75%' },
        { v: 'cw-1-1', t: '100%' },
    ],
    md_size: [
        { v: 'w-1-3', t: '33%' },
        { v: 'w-1-2', t: '50%' },
        { v: 'w-3-5', t: '60%' },
        { v: 'w-4-5', t: '80%' },
    ],
    pos: [
        { v: 'p-r', t: 'Relative' },
        { v: 'p-a', t: 'Absolute' },
    ],
    ag: [
        { v: '', t: 'None' },
        { v: 'jag ga-fade-in', t: 'Fade In' },
    ],
    fw: [
        { v: '', t: 'Normal' },
        { v: 'fw-600', t: 'Bold' },
    ],
    tag: [
        { v: 'h1', t: 'Heading 1' },
        { v: 'h2', t: 'Heading 2' },
        { v: 'h3', t: 'Heading 3' },
        { v: 'h4', t: 'Heading 4' },
        { v: 'h5', t: 'Heading 5' },
        { v: 'h6', t: 'Heading 6' },
    ],
    but_style: [
        { v: '', t: 'Simple Link' },
        { v: 'but-normal', t: 'Normal' },
        { v: 'but-small', t: 'Small' },
        { v: 'but-large', t: 'Large' },
        { v: 'but-extra-large', t: 'Extra Large' }
    ],
    but: [
        { v: 'but-blue', t: 'blue' },
        { v: 'but-green', t: 'green' },
        { v: 'but-red', t: 'red' },
        { v: 'but-grey', t: 'grey' },
        { v: 'but-indigo', t: 'indigo' },
        { v: 'but-orange', t: 'orange' },
        { v: 'but-cyan', t: 'orange' },
        { v: 'but-purple', t: 'orange' },
        { v: 'but-yellow', t: 'yellow' },
        { v: 'but-teal', t: 'teal' },
        { v: 'but-default', t: 'simple' },
    ],
    p: [
        { v: '', t: 'None' },
        { v: 'p-05', t: 'All 0.5rem' },
        { v: 'p-1', t: 'All 1rem' },
        { v: 'p-2', t: 'All 2rem' },
        { v: 'p-3', t: 'All 3rem' },
        { v: 'p-4', t: 'All 4rem' },
        { v: 'p-5', t: 'All 5rem' },
        { v: 'pv-05', t: 'Vertically 0.5rem' },
        { v: 'pv-1', t: 'Vertically 1rem' },
        { v: 'pv-2', t: 'Vertically 2rem' },
        { v: 'pv-3', t: 'Vertically 3rem' },
        { v: 'pv-4', t: 'Vertically 4rem' },
        { v: 'pv-5', t: 'Vertically 5rem' },
        { v: 'ph-05', t: 'Horizontally 0.5rem' },
        { v: 'ph-1', t: 'Horizontally 1rem' },
        { v: 'ph-2', t: 'Horizontally 2rem' },
        { v: 'ph-3', t: 'Horizontally 3rem' },
        { v: 'ph-4', t: 'Horizontally 4rem' },
        { v: 'ph-5', t: 'Horizontally 5rem' },
    ],
    ph: [
        { v: '', t: 'Default' },
        { v: 'ph-05', t: 'Horizontally 0.5rem' },
        { v: 'ph-1', t: 'Horizontally 1rem' },
        { v: 'ph-2', t: 'Horizontally 2rem' },
        { v: 'ph-3', t: 'Horizontally 3rem' },
        { v: 'ph-4', t: 'Horizontally 4rem' },
        { v: 'ph-5', t: 'Horizontally 5rem' },
    ],
    g: [
        { v: '', t: 'None' },
        { v: 'g-25', t: '0.25rem' },
        { v: 'g-05', t: '0.5rem' },
        { v: 'g-1', t: '1rem' },
        { v: 'g-2', t: '2rem' },
        { v: 'g-3', t: '3rem' },
        { v: 'g-4', t: '4rem' },
        { v: 'g-5', t: '5rem' },
    ],
    m: [
        { v: '', t: 'Default' },
        { v: 'm-0', t: '0' },
        { v: 'mv-25', t: 'Vertically 0.25rem' },
        { v: 'mv-05', t: 'Vertically 0.5rem' },
        { v: 'mv-1', t: 'Vertically 1rem' },
        { v: 'mv-2', t: 'Vertically 2rem' },
        { v: 'mv-3', t: 'Vertically 3rem' },
        { v: 'mv-4', t: 'Vertically 4rem' },
        { v: 'mv-5', t: 'Vertically 5rem' },
        { v: 'mh-25', t: 'Horizontally 0.25rem' },
        { v: 'mh-05', t: 'Horizontally 0.5rem' },
        { v: 'mh-1', t: 'Horizontally 1rem' },
        { v: 'mh-2', t: 'Horizontally 2rem' },
        { v: 'mh-3', t: 'Horizontally 3rem' },
        { v: 'mh-4', t: 'Horizontally 4rem' },
        { v: 'mh-5', t: 'Horizontally 5rem' },
        { v: ' m-25', t: ' 0.25rem' },
        { v: ' m-05', t: ' 0.5rem' },
        { v: ' m-1', t: ' 1rem' },
        { v: ' m-2', t: ' 2rem' },
        { v: ' m-3', t: ' 3rem' },
        { v: ' m-4', t: ' 4rem' },
        { v: ' m-5', t: ' 5rem' },
    ],
    ba: [
        { v: 'ba-s', t: 'Scroll' },
        { v: 'ba-f', t: 'Fixed' },
    ],
    bp: [
        { v: 'bp-cc', t: 'Center Center' },
        { v: 'bp-ct', t: 'Center Top' },
        { v: 'bp-cb', t: 'Center Bottom' },

    ],
    yes_no: [
        { v: true, t: 'Yes' },
        { v: false, t: 'No' },
    ],
    w: [

        { v: 'g-container', t: 'Grid 1200' },
        { v: 'g-fluid', t: 'Grid Fluid' },
        { v: 'g-full', t: 'Grid Full Width' },
        { v: 'w-container', t: 'Flex 1200' },
        { v: 'w-fluid', t: 'Flex Fluid' },
        { v: 'w-full', t: 'Flex Full Width' },

        // { v: 'g-container gr-2', t: 'Grid 2' },
        // { v: 'g-container gr-3', t: 'Grid 3' },
        // { v: 'g-container gr-2-1', t: 'Grid ' },
        // { v: 'g-container gr-1-2', t: 'Grid 66/33' },
        // { v: 'g-container gr-3-1', t: 'Grid 33/66' },
        // { v: 'g-container gr-1-3', t: 'Grid 75/25' },
        // { v: 'g-container gr-3-2', t: 'Grid 60/40' },
        // { v: 'g-container gr-2-3', t: 'Grid 40/60' },
    ],
    grw: [//group width
        { v: 'gr-2', t: 'Grid 2' },
        { v: 'gr-3', t: 'Grid 3' },
        { v: 'gr-4', t: 'Grid 4' },
        { v: 'gr-5', t: 'Grid 5' },
        { v: 'gr-6', t: 'Grid 6' },
        { v: 'jc-c', t: 'Flex Center' },
        { v: 'jc-s', t: 'Flex Lfet' },
        { v: 'jc-e', t: 'Flex Right' },
        { v: 'fd-c ai-c', t: 'Column Center' },
        { v: 'fd-c ai-s', t: 'Column Left' },
        { v: 'fd-c ai-e', t: 'Column Right' },
        { v: 'gr-1', t: 'Grid 1' },
    ],
    go: [
        { v: '', t: 'No' },
        { v: 'gr-2', t: 'Grid Equal 2' },
        { v: 'gr-3', t: 'Grid Equal 3' },
        { v: 'gr-3', t: 'Grid Equal 4' },
        { v: 'gr-2-1', t: 'Grid 66/33' },
        { v: 'gr-1-2', t: 'Grid 33/66' },
        { v: 'gr-3-1', t: 'Grid 75/25' },
        { v: 'gr-1-3', t: 'Grid 25/75' },
        { v: 'gr-3-2', t: 'Grid 60/40' },
        { v: 'gr-2-3', t: 'Grid 40/60' },
    ],
    wg: [
        { v: 'w-container', t: 'Container flex 1200' },
        { v: 'w-fluid', t: 'Fluid Flex' },
        { v: 'w-full', t: 'Full Flex' },
    ],
    gr: [
        { v: 'gr-1', t: 'Grid 100%' },
        { v: 'gr-2', t: 'Grid 2 x 50%' },
        { v: 'gr-3', t: 'Grid 3 x 33%' },
        { v: 'gr-4', t: 'Grid 4 x %25%' },
        { v: 'gr-5', t: 'Grid 5 x 20 %' },
        { v: 'gr-6', t: 'Grid 6 x 16%' },
        // { v: 'gr-1-1', t: 'Grid %' },
        { v: 'gr-2-1', t: 'Grid 66 x 33 %' },
        { v: 'gr-1-2', t: 'Grid 33 x 66%' },
        { v: 'gr-3-1', t: 'Grid 75 x 25%' },
        { v: 'gr-1-3', t: 'Grid 25 x 75%' },
        { v: 'gr-4-1', t: 'Grid 80 20%' },
        { v: 'gr-1-4', t: 'Grid 20 x 80%' },
        { v: 'gr-3-2', t: 'Grid 60 x 40%' },
        { v: 'gr-2-3', t: 'Grid 40 x 60 %' },
    ],
    jc: [
        { v: 'jc-c', t: 'Center' },
        { v: 'jc-b', t: 'Space-between' },
        { v: 'jc-s', t: 'Start' },
        { v: 'jc-e', t: 'End' },
        { v: 'jc-a', t: 'Space-around' },
        { v: 'jc-ev', t: 'Space-evenly' },
    ],
    ai: [
        { v: 'ai-s', t: 'Start' },
        { v: 'ai-e', t: 'End' },
        { v: 'ai-b', t: 'Baseline' },
        { v: 'ai-st', t: 'Stretch' },
        { v: 'ai-c', t: 'Center' },
    ],
    ss_v: [
        { v: 'ai-s', t: 'Top' },
        { v: 'ai-c', t: 'Center' },
        { v: 'ai-e', t: 'Bottom' },
    ],
    ss_h: [
        { v: 'ai-s', t: 'Left' },
        { v: 'ai-c', t: 'Center' },
        { v: 'ai-e', t: 'Right' },
    ],
    fd_simple: [
        { v: 'fd-r', t: 'Horizontal' },
        { v: 'fd-c', t: 'Vertical' },
    ],
    fd: [
        { v: '', t: 'Row' },
        { v: 'fd-c', t: 'Column' },
        { v: 'fd-rr', t: 'Row Reverse' },
        { v: 'fd-cr', t: 'Column Reverse' },
    ],
    fs: [
        { v: 'fd-r', t: 'Row' },
        { v: 'fs-8', t: '0.8 rem' },
        { v: 'fs-9', t: '0.9 rem' },
        { v: 'fs-10', t: '1 rem' },
        { v: 'fs-11', t: '1.1 rem' },
        { v: 'fs-12', t: '1.2 rem' },
        { v: 'fs-13', t: '1.3 rem' },
        { v: 'fs-14', t: '1.4 rem' },
        { v: 'fs-15', t: '1.5 rem' },
        { v: 'fs-16', t: '1.6 rem' },
        { v: 'fs-17', t: '1.7 rem' },
        { v: 'fs-18', t: '1.8 rem' },
        { v: 'fs-19', t: '1.9 rem' },
        { v: 'fs-20', t: '2 rem' },
        { v: 'fs-21', t: '2.1 rem' },
        { v: 'fs-22', t: '2.2 rem' },
        { v: 'fs-23', t: '2.3 rem' },
        { v: 'fs-24', t: '2.4 rem' },
        { v: 'fs-25', t: '2.5 rem' },
        { v: 'fs-26', t: '2.6 rem' },
        { v: 'fs-27', t: '2.7 rem' },
        { v: 'fs-28', t: '2.8 rem' },
        { v: 'fs-29', t: '2.9 rem' },
        { v: 'fs-30', t: '3 rem' },
        { v: 'fs-31', t: '3.1 rem' },
        { v: 'fs-32', t: '3.2 rem' },
        { v: 'fs-33', t: '3.3 rem' },
        { v: 'fs-34', t: '3.4 rem' },
        { v: 'fs-35', t: '3.5 rem' },
    ],
    size: [
        { v: 'fd-r', t: 'Row' },
        { v: 'fs-8', t: '0.8 rem' },
        { v: 'fs-9', t: '0.9 rem' },
        { v: 'fs-10', t: '1 rem' },
        { v: 'fs-11', t: '1.1 rem' },
        { v: 'fs-12', t: '1.2 rem' },
        { v: 'fs-13', t: '1.3 rem' },
        { v: 'fs-14', t: '1.4 rem' },
        { v: 'fs-15', t: '1.5 rem' },
        { v: 'fs-16', t: '1.6 rem' },
        { v: 'fs-17', t: '1.7 rem' },
        { v: 'fs-18', t: '1.8 rem' },
        { v: 'fs-19', t: '1.9 rem' },
        { v: 'fs-20', t: '2 rem' },
        { v: 'fs-21', t: '2.1 rem' },
        { v: 'fs-22', t: '2.2 rem' },
        { v: 'fs-23', t: '2.3 rem' },
        { v: 'fs-24', t: '2.4 rem' },
        { v: 'fs-25', t: '2.5 rem' },
        { v: 'fs-26', t: '2.6 rem' },
        { v: 'fs-27', t: '2.7 rem' },
        { v: 'fs-28', t: '2.8 rem' },
        { v: 'fs-29', t: '2.9 rem' },
        { v: 'fs-30', t: '3 rem' },
        { v: 'fs-31', t: '3.1 rem' },
        { v: 'fs-32', t: '3.2 rem' },
        { v: 'fs-33', t: '3.3 rem' },
        { v: 'fs-34', t: '3.4 rem' },
        { v: 'fs-35', t: '3.5 rem' },
    ],
    bs: [
        { v: '', t: 'none' },
        { v: 'bs-1', t: 'Depth 1' },
        { v: 'bs-2', t: 'Depth 2' },
        { v: 'bs-3', t: 'Depth 3' },
        { v: 'bs-4', t: 'Depth 4' },
        { v: 'bs-5', t: 'Depth 5' },
        { v: 'bs-5', t: 'Depth 6' },
        { v: 'bs-7', t: 'Depth 7' },
    ],
    radius: [
        { v: '', t: 'none' },
        { v: 'br-1', t: '1px' },
        { v: 'br-2', t: '2px' },
        { v: 'br-3', t: '3px' },
        { v: 'br-4', t: '4px' },
        { v: 'br-5', t: '5px' },
        { v: 'br-6', t: '6px' },
        { v: 'br-7', t: '7px' },
        { v: 'br-8', t: '8px' },
        { v: 'br-9', t: '9px' },
        { v: 'br-10', t: '10px' },
        { v: 'br-11', t: '11px' },
        { v: 'br-12', t: '12px' },
        { v: 'br-13', t: '13px' },
        { v: 'br-14', t: '14px' },
        { v: 'br-15', t: '15px' },
        { v: 'br-16', t: '16px' },
        { v: 'br-17', t: '17px' },
        { v: 'br-18', t: '18px' },
        { v: 'br-19', t: '19px' },
        { v: 'br-20', t: '20px' },
        { v: 'br-21', t: '21px' },
        { v: 'br-22', t: '22px' },
        { v: 'br-23', t: '23px' },
        { v: 'br-24', t: '24px' },
        { v: 'br-25', t: '25px' },
    ],
};
